name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Shell MFE Image (test build)
      - name: Build Shell MFE Image
        uses: docker/build-push-action@v5
        with:
          context: ./shell
          push: false
          tags: shell-mfe:latest

      # Build Remote MFE Image (test build)
      - name: Build Remote MFE Image
        uses: docker/build-push-action@v5
        with:
          context: ./remote
          push: false
          tags: remote-mfe:latest