name: Build Micro-Frontend Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Build Shell MFE Image
      - name: Build Shell MFE Docker image
        run: docker build ./apps/shell --file ./shell/Dockerfile --tag shell-mfe:$(date +%s)

      # 2. Build Remote MFE Image
      - name: Build Remote MFE Docker image
        run: docker build ./apps/remote --file ./remote/Dockerfile --tag remote-mfe:$(date +%s)